# Generated by Django 3.2.23 on 2023-11-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('previous_jobs_count', models.IntegerField(default=0)),
                ('amount_due', models.CharField(max_length=20)),
                ('lat', models.CharField(max_length=20)),
                ('long', models.CharField(max_length=20)),
            ],
        ),
    ]
